"use client";
import React from "react";

type CreativeReviewModalProps = {
  isOpen: boolean;
  data: Record<string, any[]> | null;
  onClose: () => void;
};

export function CreativeReviewModal({ isOpen, data, onClose }: CreativeReviewModalProps) {
  if (!isOpen || !data) return null;

  // Flatten the dictionary into a single array of posts so it's easy to scroll
  const allPosts = Object.entries(data).flatMap(([date, entries]) => 
    entries.map(entry => ({ date, ...entry }))
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden border border-gray-200">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 bg-gray-50 flex justify-between items-center">
          <div>
            <h2 className="text-xl font-black tracking-tight text-gray-900">Phase 3: Creative Fill Complete</h2>
            <p className="text-sm text-gray-500">Review the copy and visual directions generated by your AI team.</p>
          </div>
          <div className="flex gap-2">
            <span className="px-3 py-1 bg-green-100 text-green-700 text-xs font-bold rounded-full">
              {allPosts.length} Posts Ready
            </span>
          </div>
        </div>

        {/* Scrollable Feed */}
        <div className="flex-1 overflow-y-auto p-6 bg-gray-100 custom-scrollbar">
          <div className="space-y-6 max-w-2xl mx-auto">
            {allPosts.map((post, idx) => (
              <div key={idx} className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                
                {/* Post Header (Date & Platform) */}
                <div className="px-5 py-3 border-b border-gray-100 flex justify-between items-center bg-gray-50">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm text-gray-700">{post.date}</span>
                    <span className="text-xs text-gray-400">•</span>
                    <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">{post.skeleton?.platform}</span>
                  </div>
                  <span className="text-xs font-bold px-2 py-1 bg-gray-200 text-gray-600 rounded">
                    {post.skeleton?.content_type}
                  </span>
                </div>

                {/* Post Content */}
                <div className="p-5 space-y-4">
                  
                  {/* Copy Area */}
                  <div>
                    <h4 className="text-xs font-black text-gray-400 uppercase tracking-widest mb-1">Leo (Copywriter)</h4>
                    <div className="p-4 bg-gray-50 rounded-lg border border-gray-100">
                      <p className="font-bold text-gray-900 mb-2">{post.creative?.hook}</p>
                      <p className="text-gray-700 text-sm whitespace-pre-wrap leading-relaxed">{post.creative?.caption}</p>
                      <p className="text-blue-600 text-sm mt-2 font-medium">{post.creative?.hashtags?.join(" ")}</p>
                      <p className="text-gray-900 font-bold text-sm mt-2">↳ {post.creative?.cta}</p>
                    </div>
                  </div>

                  {/* Visual Area */}
                  <div>
                    <h4 className="text-xs font-black text-gray-400 uppercase tracking-widest mb-1">Maria (Art Director)</h4>
                    <div className="p-4 bg-purple-50 rounded-lg border border-purple-100 flex gap-3">
                      <div className="text-xl">📸</div>
                      <div>
                        <p className="text-sm text-purple-900 font-bold mb-1">Mood: {post.creative?.visual_direction?.mood}</p>
                        <p className="text-sm text-purple-800 italic">{post.creative?.visual_direction?.style_hint}</p>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-100 bg-white flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2.5 bg-black text-white font-bold rounded-lg hover:bg-gray-800 transition-colors shadow-md"
          >
            Acknowledge & Close
          </button>
        </div>

      </div>
    </div>
  );
}